spring:
  application:
    name: eureka-consumer-feign-hystrix
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 8003
feign:
  hystrix:
    enabled: true

#用来暴露 endpoints
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream